### ISSUE TITLE
Missing react dependencies

### ISSUE THREAD

**Issue by victords** [samuelayo/typescript-react#1]
Hi there,

First, let me thank you for setting this project up... I was looking for a way to run a react app with TypeScript without a server and with the least possible configuration, and this is exactly what I hoped. Thanks!

Now, when I cloned the repo and followed the steps in the readme, It didn't work at first, for two reasons:

- I had to run "npm link typescript" to use the globally installed TypeScript.
- After that the compilation failed, because react itself was not installed. So I simply added the "react" and "react-dom" packages as dependencies and run "npm install" again.

So to "fix" the process you would only need to edit the package.json to include the react dependencies and the readme.md to include the "npm link typescript" step.

Sorry if I missed anything and thanks.

**Comment by samuelayo** [comment]
hi @victords, could you please submit a pull request on this? Thanks for helping out with that.

**Comment by victords** [comment]
There you go.

**Comment by samuelayo** [comment]
Thanks
